---
- name: Restart services
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_dir }}"
    state: present
    recreate: "always"
    pull: "always"
  register: restart_result

- name: Show restart results
  ansible.builtin.debug:
    var: restart_result
